// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwiOdp7fzdLd3mAYoK2zR2XGfYXzFzpnA',
    appId: '1:738663675010:web:3753e86ea18302fb54b09b',
    messagingSenderId: '738663675010',
    projectId: 'chetna-healthhack',
    authDomain: 'chetna-healthhack.firebaseapp.com',
    databaseURL: 'https://chetna-healthhack-default-rtdb.firebaseio.com',
    storageBucket: 'chetna-healthhack.firebasestorage.app',
    measurementId: 'G-JPZVKKBNW1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi3TQ3LMvQDVEenuKVqRIfADF1X_lgAPM',
    appId: '1:738663675010:android:d54efb09c4a43e0954b09b',
    messagingSenderId: '738663675010',
    projectId: 'chetna-healthhack',
    databaseURL: 'https://chetna-healthhack-default-rtdb.firebaseio.com',
    storageBucket: 'chetna-healthhack.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcVDK3bNvSQtpF3r8RdYwsCTiIY5kKrTo',
    appId: '1:738663675010:ios:387261bf52afe60054b09b',
    messagingSenderId: '738663675010',
    projectId: 'chetna-healthhack',
    databaseURL: 'https://chetna-healthhack-default-rtdb.firebaseio.com',
    storageBucket: 'chetna-healthhack.firebasestorage.app',
    iosBundleId: 'com.example.chetnaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcVDK3bNvSQtpF3r8RdYwsCTiIY5kKrTo',
    appId: '1:738663675010:ios:387261bf52afe60054b09b',
    messagingSenderId: '738663675010',
    projectId: 'chetna-healthhack',
    databaseURL: 'https://chetna-healthhack-default-rtdb.firebaseio.com',
    storageBucket: 'chetna-healthhack.firebasestorage.app',
    iosBundleId: 'com.example.chetnaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwiOdp7fzdLd3mAYoK2zR2XGfYXzFzpnA',
    appId: '1:738663675010:web:3b75a2d390b8cbad54b09b',
    messagingSenderId: '738663675010',
    projectId: 'chetna-healthhack',
    authDomain: 'chetna-healthhack.firebaseapp.com',
    databaseURL: 'https://chetna-healthhack-default-rtdb.firebaseio.com',
    storageBucket: 'chetna-healthhack.firebasestorage.app',
    measurementId: 'G-PL42WYBXNC',
  );
}
